### ISSUE TITLE
Memory access error while installing deepqmc on AMD MI 300 GPU systems

### ISSUE THREAD

**Issue by bharath1996-hub** [deepqmc/deepqmc#220]
Hi all, I am trying to install and run deepqmc on AMD Mi300 GPU systems. When i test the installation, i am getting an errror at pyscf step as Memory access fault by GPU node-4. Any help is highly appreciated. 

(deepqmc) Bcmum@2b5e6e0bd62b:~/work/deepqmc/workdir/training$ deepqmc
[2025-05-06 08:27:49.147] INFO:deepqmc.app: Entering application
[2025-05-06 08:27:58.116] INFO:deepqmc.app: Process 0 running on 2b5e6e0bd62b
[2025-05-06 08:27:58.117] INFO:deepqmc.app: Running on 4 AMD INSTINCT MI300As with 1 process
[2025-05-06 08:27:58.117] INFO:deepqmc.app: Will work in /datasets/teams/dcgpu_training/hlrs/Bcmum/work/deepqmc/workdir/training/outputs/2025-05-06/08-27-49
[2025-05-06 08:27:58.290] DEBUG:deepqmc.app: Running with code version: 79572cb
[2025-05-06 08:28:09.587] DEBUG:deepqmc.train: Setting up metric_logger...
[2025-05-06 08:28:09.594] DEBUG:deepqmc.train: Setting up h5_logger...
[2025-05-06 08:29:06.722] INFO:deepqmc.wf.base: Number of model parameters: 197589
[2025-05-06 08:29:23.280] INFO:deepqmc.train: Pretraining wrt. baseline wave function
[2025-05-06 08:29:24.848] INFO:deepqmc.pretrain.pyscfext: Running HF...
[2025-05-06 08:29:25.953] INFO:deepqmc.pretrain.pyscfext: HF energy: -7.951971538662554
[2025-05-06 08:29:25.954] INFO:deepqmc.pretrain.pyscfext: Dump PySCF checkpoint to /datasets/teams/dcgpu_training/hlrs/Bcmum/work/deepqmc/workdir/training/outputs/2025-05-06/08-27-49/training/pyscf_chkpts/mol_0.pyscf_chkpt
**Hip error: 'operation would make the legacy stream depend on a capturing blocking stream'(906) at /longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/hipBLASLt/library/src/amd_detail/hipblaslt.cpp:172
Hip error: 'operation would make the legacy stream depend on a capturing blocking stream'(906) at /longer_pathname_so_that_rpms_can_support_packaging_the_debug_info_for_all_os_profiles/src/hipBLASLt/library/src/amd_detail/hipblaslt.cpp:172
Memory access fault by GPU node-4 (Agent handle: 0x60c0e3e54110) on address 0x7a8bfd559000. Reason: Unknown.
Segmentation fault (core dumped)**

the list of packages:

absl-py==2.2.2
antlr4-python3-runtime==4.9.3
attrs==25.3.0
black==25.1.0
cfgv==3.4.0
chex==0.1.89
click==8.1.8
cloudpickle==3.1.1
codespell==2.4.1
decorator==5.2.1
-e git+https://github.com/deepqmc/deepqmc@79572cbd6dfcfc159ca60f2b61f0538b124b5994#egg=deepqmc
distlib==0.3.9
distrax==0.1.5
dm-haiku==0.0.14
dm-tree==0.1.9
etils==1.12.2
exceptiongroup==1.2.2
filelock==3.18.0
flake8==7.2.0
flake8-bugbear==24.12.12
flake8-comprehensions==3.16.0
flake8-quotes==3.4.0
gast==0.6.0
h5py==3.13.0
hydra-core==1.3.2
identify==2.6.10
immutabledict==4.2.1
iniconfig==2.1.0
isort==6.0.1
jax @ file:///tmp/jax
jax-rocm60-pjrt @ file:///tmp/jax/dist/jax_rocm60_pjrt-0.4.35.dev20250426-py3-none-manylinux2014_x86_64.whl
jax-rocm60-plugin @ file:///tmp/jax/dist/jax_rocm60_plugin-0.4.35.dev20250426-cp310-cp310-manylinux2014_x86_64.whl
jax_dataclasses==1.6.2
jaxlib==0.4.35
jmp==0.0.4
kfac-jax==0.0.6
mccabe==0.7.0
ml_dtypes==0.5.1
mypy==1.15.0
mypy_extensions==1.1.0
nodeenv==1.9.1
numpy==2.2.5
omegaconf==2.3.0
opt_einsum==3.4.0
optax==0.2.4
packaging==25.0
pathspec==0.12.1
pep8-naming==0.15.1
platformdirs==4.3.7
pluggy==1.5.0
pre_commit==4.2.0
protobuf==6.30.2
pycodestyle==2.13.0
pydocstyle==6.3.0
pyflakes==3.3.2
pyright==1.1.400
pyscf==2.9.0
pytest==8.3.5
pytest-datadir==1.6.1
pytest-regressions==2.7.0
PyYAML==6.0.2
scipy==1.15.2
six==1.17.0
snowballstemmer==2.2.0
tabulate==0.9.0
tensorboardX==2.6.2.2
tensorflow-probability==0.25.0
tomli==2.2.1
toolz==1.0.0
tqdm==4.67.1
typing_extensions==4.13.2
uncertainties==3.2.3
virtualenv==20.31.1
wrapt==1.17.2

**Comment by szbernat** [comment]
Hi,

Thanks for trying `deepqmc`!

Unfortunately, we don't have access to AMD GPUs and therefore `deepqmc` was never tested with this hardware.Your error looks like a low level problem with JAX and ROCm, which is triggered by one of the operations in `deepqmc`. As a workaround you could try to skip the pretraining stage in which the error occurs (pretraining is not strictly necessary for accurate results). You can do this with the command `deepqmc task.pretrain_steps=0`.

To be able to understand the actual error, it would be helpful to know exactly which `deepqmc` operation is triggering it. This would most likely involve editing the `deepqmc` source code, e.g.: adding print statements to determine which line is causing the error. If you are feeling up to this we are happy to give you support, but unfortunately we won't be able to do this ourselves due to not having access to AMD GPUs.

**Comment by bharath1996-hub** [comment]
Hi, 

I got the installation working. It is problem of installing jax and jax-lib as the rocm does not support the jax that gets installed while installing the repo. 

One has to build the jax wheel from source and load the module and then clone the deepqmc repository. In some cases, it will also help if you can comment out the "jax" and "jax-lib" in pyproject.toml file while installing other dependencies.

**Comment by szbernat** [comment]
Hi,

Great to hear! We'd be curious to hear how working with `deepqmc` goes on an AMD GPU, because as I mentioned above, we haven't yet tested it on that hardware. I'm closing this issue since the concrete error is resolved, but feel free to open a new one if anything else comes up.
